import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'

test('font preferences apply independently, survive reload, and work on mobile', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/library', { waitUntil: 'networkidle' })
  await page.getByTestId('app-language-option-en').click()
  await page.locator('input[type=file]').setInputFiles(path.join(process.cwd(), 'scripts/fixtures/workspace-import-smoke.txt'))
  await page.waitForURL(/\/workspace/)
  const editor = page.locator('.ProseMirror')
  await expect(editor).toBeVisible()
  const originalReadingFont = await editor.evaluate((element) => getComputedStyle(element).fontFamily)
  const originalInterfaceFont = await page.locator('body').evaluate((element) => getComputedStyle(element).fontFamily)

  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Settings', exact: true })
  await expect(dialog.getByRole('button', { name: 'Appearance', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('option')).toHaveCount(22)
  await dialog.getByLabel('Interface font', { exact: true }).selectOption('arial')
  await expect(page.locator('body')).toHaveCSS('font-family', /^Arial,/)
  await expect(editor).toHaveCSS('font-family', originalReadingFont)
  await dialog.getByLabel('Reading & writing font', { exact: true }).selectOption('georgia')
  await expect(editor).toHaveCSS('font-family', /^Georgia,/)
  await expect(dialog.getByRole('status')).toHaveText('Changes apply instantly and are saved in this browser.')

  const evidenceDir = path.join(process.cwd(), '.sisyphus/evidence/font-preferences')
  fs.mkdirSync(evidenceDir, { recursive: true })
  await page.screenshot({ path: path.join(evidenceDir, 'desktop.png'), animations: 'disabled' })

  await page.keyboard.press('Escape')
  await page.reload({ waitUntil: 'networkidle' })
  await expect(page.locator('body')).toHaveCSS('font-family', /^Arial,/)
  await expect(editor).toHaveCSS('font-family', /^Georgia,/)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(dialog.getByLabel('Interface font', { exact: true })).toHaveValue('arial')
  await expect(dialog.getByLabel('Reading & writing font', { exact: true })).toHaveValue('georgia')
  await dialog.getByRole('button', { name: 'AI models', exact: true }).click()
  await expect(dialog.getByTestId('ai-settings-scenario-embeddings')).toBeVisible()
  await dialog.getByRole('button', { name: 'Appearance', exact: true }).click()
  await dialog.getByLabel('Reading & writing font', { exact: true }).selectOption('kaiti')
  await expect(editor).toHaveCSS('font-family', /^KaiTi,/)
  await page.keyboard.press('Escape')

  await page.goto('/library', { waitUntil: 'networkidle' })
  await expect(page.locator('body')).toHaveCSS('font-family', /^Arial,/)
  await page.getByTestId('app-language-option-zh').click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/workspace', { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: '更多选项', exact: true }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  const mobileDialog = page.getByRole('dialog', { name: '设置', exact: true })
  await expect(mobileDialog.getByLabel('阅读与写作字体', { exact: true })).toHaveValue('kaiti')
  await expect(mobileDialog).toHaveCSS('opacity', '1')
  await page.screenshot({ path: path.join(evidenceDir, 'mobile.png'), animations: 'disabled' })
  expect(await mobileDialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await mobileDialog.getByRole('button', { name: '恢复默认字体' }).click()
  await expect(page.locator('body')).toHaveCSS('font-family', originalInterfaceFont)
  await expect(editor).toHaveCSS('font-family', originalReadingFont)
  await expect(mobileDialog.getByRole('button', { name: '恢复默认字体' })).toBeDisabled()
  await page.keyboard.press('Escape')
  await page.reload({ waitUntil: 'networkidle' })
  await expect(editor).toHaveCSS('font-family', originalReadingFont)
  expect(errors).toEqual([])
})
